/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SIC.Vistas;

import SIC.Vistas.tableModels.CargosTableModel;
import SIC.Entidades.Cargo;
import SIC.Service.SICService;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.xml.ws.Service;

public class Cargos extends javax.swing.JFrame {

    public CargosTableModel CargoTModel = new CargosTableModel();
    Cargo cargoActual;
    boolean guardar;

    public Cargos() {

        initComponents();
        inicializarColumnas();
        cargarListaCargos();

    }

    private void inicializarColumnas() {
        TableColumnModel tColumnModel = new DefaultTableColumnModel();
        for (int i = 0; i < 2; i++) {
            TableColumn col = new TableColumn(i);
            switch (i) {
                case 0:
                    col.setHeaderValue("Sueldo");
                    break;
                case 1:
                    col.setHeaderValue("Nombre Cargo");
                    break;
            }
            tColumnModel.addColumn(col);
        }
        tablaCargos.setColumnModel(tColumnModel);
    }

    private void cargarListaCargos() {
        CargoTModel.cargos = SICService.getServCargo().getListado();
        tablaCargos.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SistemaContablePU").createEntityManager();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        sueldoTxt = new javax.swing.JTextField();
        BtonGuardarCargo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCargos = new javax.swing.JTable();
        BtonEliminarCargo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cargos ");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Sueldo:");

        BtonGuardarCargo.setText("Guardar");
        BtonGuardarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonGuardarCargoActionPerformed(evt);
            }
        });

        tablaCargos.setModel(CargoTModel);
        tablaCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCargosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCargos);

        BtonEliminarCargo.setText("Eliminar");
        BtonEliminarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonEliminarCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(sueldoTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(BtonGuardarCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtonEliminarCargo)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sueldoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtonGuardarCargo)
                    .addComponent(BtonEliminarCargo))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtonGuardarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonGuardarCargoActionPerformed
        // TODO add your handling code here:
        Cargo cargo = new Cargo();
        String nombre = nombreTxt.getText();
        Float sueldo = Float.parseFloat(sueldoTxt.getText());
        cargo.setNombreCargo(nombre);
        cargo.setSueldo(sueldo);
        
        if (cargo == null) {
            JOptionPane.showMessageDialog(null, "Datos Vacios ingrese bien los datos");
        } else {
            if (cargoActual == null) {
                SICService.getServCargo().guardar(cargo);
                JOptionPane.showMessageDialog(null, "Datos guardados");
                cargarListaCargos();
                //JOptionPane.showMessageDialog(null, "Por favor complete los datos");
            } else {

                if (cargoActual.getIdCargo() != null) {
                    cargo = new Cargo(cargoActual.getIdCargo());
                } else {
                    cargo = cargoActual;
                }
                cargoActual.setNombreCargo(nombre);
                cargoActual.setSueldo(sueldo);
                cargarListaCargos();
            }
        }

    }//GEN-LAST:event_BtonGuardarCargoActionPerformed

    private void BtonEliminarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonEliminarCargoActionPerformed
        // TODO add your handling code here:

        if (cargoActual != null) {
            SICService.getServCargo().eliminar(cargoActual);
            JOptionPane.showMessageDialog(null, "Eliminado con éxito");
            cargarListaCargos();

        } else {
            JOptionPane.showMessageDialog(null, "No hay cargo seleccionado");
        }
    }//GEN-LAST:event_BtonEliminarCargoActionPerformed

    private void tablaCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCargosMouseClicked
        // TODO add your handling code here:
        int clics = evt.getClickCount();
        int row = tablaCargos.rowAtPoint(evt.getPoint());
        if (clics == 2) {
            Cargo cargo = CargoTModel.cargos.get(row);
            cargoActual = cargo;
            nombreTxt.setText(cargo.getNombreCargo());
            sueldoTxt.setText(String.valueOf(cargo.getSueldo()));
                    }
    }//GEN-LAST:event_tablaCargosMouseClicked

    /**
     * no
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtonEliminarCargo;
    private javax.swing.JButton BtonGuardarCargo;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField sueldoTxt;
    private javax.swing.JTable tablaCargos;
    // End of variables declaration//GEN-END:variables
}
