/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SIC.Vistas;

import java.awt.Image;
import java.util.Locale;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author Escobar
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLayout(null);
        this.setTitle("DELIFRUTAL");
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(102,177,255));
        this.setSize(968,504); 
        this.setResizable(false); 
        envio1.setSize(230,40);
        envio2.setSize(230,40);
        envio3.setSize(230,40);
        envio4.setSize(230,40);
        envio5.setSize(230,40);
        ImageIcon fot = new ImageIcon(getClass().getResource("/SIC/Imagenes/logo.png"));
        ImageIcon icono = new ImageIcon(fot.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        envio1 = new javax.swing.JButton();
        envio2 = new javax.swing.JButton();
        envio3 = new javax.swing.JButton();
        envio4 = new javax.swing.JButton();
        envio5 = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));

        jLabel1.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("DELIFRUTAL");

        jLabel2.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("EL SABOR DE LO NATURAL ");

        envio1.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        envio1.setText("REGISTRAR TRANSACCIÓN");
        envio1.setMaximumSize(new java.awt.Dimension(165, 23));
        envio1.setPreferredSize(new java.awt.Dimension(160, 25));
        envio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envio1ActionPerformed(evt);
            }
        });

        envio2.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        envio2.setText("ESTADOS FINANCIEROS");
        envio2.setPreferredSize(new java.awt.Dimension(160, 25));
        envio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envio2ActionPerformed(evt);
            }
        });

        envio3.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        envio3.setText("REGISTRAR EMPLEADO");
        envio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envio3ActionPerformed(evt);
            }
        });

        envio4.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        envio4.setText("MANTENIMIENTO DE CUENTAS");
        envio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envio4ActionPerformed(evt);
            }
        });

        envio5.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        envio5.setText("CARGOS");
        envio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envio5ActionPerformed(evt);
            }
        });

        logo.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(imagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(envio2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(envio4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(envio5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(envio1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(envio3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jLabel1)))
                .addContainerGap(536, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(imagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(envio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(envio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(envio3)
                .addGap(27, 27, 27)
                .addComponent(envio4)
                .addGap(27, 27, 27)
                .addComponent(envio5)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void envio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envio3ActionPerformed
        // TODO add your handling code here:
        RegistroEmpleado empleado= new RegistroEmpleado();
        empleado.setVisible(true);
    }//GEN-LAST:event_envio3ActionPerformed

    private void envio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envio1ActionPerformed
        // TODO add your handling code here:
        IngresoCuenta ingreso=new IngresoCuenta();
        ingreso.setVisible(true);
    }//GEN-LAST:event_envio1ActionPerformed

    private void envio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envio2ActionPerformed
        // TODO add your handling code here:
        MantenimientoEstadosFinancieros estados= new MantenimientoEstadosFinancieros();
        estados.setVisible(true);
    }//GEN-LAST:event_envio2ActionPerformed

    private void envio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envio4ActionPerformed
        // TODO add your handling code here:
        MantenimientoCuentas cuentas= new MantenimientoCuentas();
        cuentas.setVisible(true);
    }//GEN-LAST:event_envio4ActionPerformed

    private void envio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envio5ActionPerformed
        // TODO add your handling code here:
        Cargos cargos= new Cargos();
        cargos.setVisible(true);
    }//GEN-LAST:event_envio5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
                new Inicio().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton envio1;
    private javax.swing.JButton envio2;
    private javax.swing.JButton envio3;
    private javax.swing.JButton envio4;
    private javax.swing.JButton envio5;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
