/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SIC.Vistas;

import SIC.Entidades.CuentaSaldada;
import SIC.Entidades.EstadoFinanciero;
import SIC.Entidades.TipoEstadoFinanciero;
import SIC.Service.SICService;
import SIC.Vistas.tableModels.CuentasEFModel;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP TouchSmart
 */
public class MantenimientoEstadosFinancieros extends javax.swing.JFrame {
    CuentasEFModel tableModel= new CuentasEFModel();
    /**
     * Creates new form EstadosFinancieros
     */
    public MantenimientoEstadosFinancieros() {
        initComponents();
        tablaCuentasEF.setColumnModel(Comunes.crearModeloColumnas("Cuenta,Debe,Haber"));
       tiposEstadoFinanciero.setModel(Comunes.crearModeloComboBox(SICService.getServTipoEstadoFinanciero().getListado()));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCuentasEF = new javax.swing.JTable();
        tiposEstadoFinanciero = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        botonGenerar = new javax.swing.JButton();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCuentasEF.setModel(tableModel);
        jScrollPane1.setViewportView(tablaCuentasEF);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 438, 240));

        tiposEstadoFinanciero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(tiposEstadoFinanciero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 230, -1));

        jLabel2.setText("Estado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        botonGenerar.setText("Generar");
        botonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        total.setText("Total:");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarActionPerformed
        // TODO add your handling code here:
        tableModel.cuentasSaldadas.clear();
        TipoEstadoFinanciero tipoEstadoFinancieroSelected=(TipoEstadoFinanciero) tiposEstadoFinanciero.getSelectedItem();
        if(tipoEstadoFinancieroSelected.getIdTipoEstadoFinanciero().equals("EC")){
            tableModel.cuentasSaldadas=SICService.getServCuentaSaldada().findByTipoCuenta("K");
        }else if(tipoEstadoFinancieroSelected.getIdTipoEstadoFinanciero().equals("ER")){
         tableModel.cuentasSaldadas=SICService.getServCuentaSaldada().findByTipoCuenta("R");
        }else if(tipoEstadoFinancieroSelected.getIdTipoEstadoFinanciero().equals("BG")){
         tableModel.cuentasSaldadas=SICService.getServCuentaSaldada().findByTipoCuenta("A");
        }else if(tipoEstadoFinancieroSelected.getIdTipoEstadoFinanciero().equals("BC")){
         tableModel.cuentasSaldadas=SICService.getServCuentaSaldada().getListado();
         tableModel.cuentasSaldadas.removeIf(cs -> cs.getCuenta().getTipoCuenta().getIdTipoCuenta().equals("R"));
        }
        
        tableModel.fireTableDataChanged();
       
        double t=0;
        for(CuentaSaldada cuentaSaldada:tableModel.cuentasSaldadas)
        {
                t += cuentaSaldada.getSaldo();
        }
        
        if(t > 0)
            total.setText("Saldo deudor: " + t );
        else{
            t=-t;
            total.setText("Saldo acreedor: " + t);
        }
            
    }//GEN-LAST:event_botonGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoEstadosFinancieros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoEstadosFinancieros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoEstadosFinancieros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoEstadosFinancieros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoEstadosFinancieros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCuentasEF;
    private javax.swing.JComboBox<String> tiposEstadoFinanciero;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
