/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas; 

import clases.Cuenta;
import clases.LineaTransaccion;
import clases.Movimiento;
import clases.MovimientosTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import modelo.SICService;

/**
 *
 * @author Escobar
 */
public class IngresoCuenta extends javax.swing.JFrame {
    public MovimientosTableModel tabla = new MovimientosTableModel();
    List<Cuenta> cuentas= new ArrayList<>();
    DefaultComboBoxModel combo= new DefaultComboBoxModel();
    
    public IngresoCuenta() {
        this.getContentPane().setBackground(new java.awt.Color(102,177,255));
        initComponents();
        inicializarColumnas();
        combo.addElement(new Cuenta("José", "A", new Movimiento("D",500 ) ));
        combo.addElement(new Cuenta("Elsy", "P", new Movimiento("H",700 ) ));
        combo.addElement(new Cuenta("Dannier", "P", new Movimiento("H",600 ) ));
        combo.addElement(new Cuenta("Master", "A", new Movimiento("H",6100 ) ));
        comboListaCuentas.setModel(combo);
        this.setLocationRelativeTo(null);
        nombreNuevaCuenta.setVisible(false);
        Tipo.setVisible(false);
        for(Cuenta cuenta:SICService.getServCuenta().getListado()){
            String cad="\n";
            for(Movimiento movimiento:SICService.getServMovimiento().getListadoByIdCuenta(cuenta.getIdCuenta()))
                cad+=movimiento.getTipo() + " " + movimiento.getCantidad() + "\n";
            
            JOptionPane.showMessageDialog(null, cuenta.getNombre() +cad);
        }
    }
    
    private void inicializarColumnas() {
        TableColumnModel tColumnModel = new DefaultTableColumnModel();
        for (int i = 0; i < 3; i++) {
        TableColumn col = new TableColumn(i);
        switch (i) {
            case 0:
                col.setHeaderValue("Nombre de la cuenta");
                break;
            case 1:
                col.setHeaderValue("Tipo de transacción");
                break;
            case 2:
                col.setHeaderValue("Monto");
                break;
        }
        tColumnModel.addColumn(col);
        }
        jTable1.setColumnModel(tColumnModel);
       
}

    public boolean isAdd(Cuenta cuenta){
        for(LineaTransaccion linea: tabla.lineas){
            if(linea.getCuenta().equals(cuenta))
                return true;
            }
        return false;
    }
    
    public boolean total (){
        double resultado=0;
        for (LineaTransaccion linea: tabla.lineas) {
            if(linea.getTransaccion().getTipo()=="D")
                resultado+=linea.getTransaccion().getCantidad();
            else
                resultado-=linea.getTransaccion().getCantidad();
        }
        if(resultado==0)
            return true;
        else
            return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoCuenta = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        comboListaCuentas = new javax.swing.JComboBox();
        montoMovimiento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreNuevaCuenta = new javax.swing.JTextField();
        Crear = new javax.swing.JCheckBox();
        Tipo = new javax.swing.JComboBox();
        aplicaIva = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 700));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRO DE TRANSACCIONES ");

        jTable1.setModel(tabla);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        comboListaCuentas.setEditable(true);
        comboListaCuentas.setMaximumSize(new java.awt.Dimension(28, 20));
        comboListaCuentas.setName(""); // NOI18N
        comboListaCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboListaCuentasActionPerformed(evt);
            }
        });

        montoMovimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        montoMovimiento.setText("Monto");
        montoMovimiento.setToolTipText("Monto");
        montoMovimiento.setMaximumSize(new java.awt.Dimension(7, 70));
        montoMovimiento.setMinimumSize(new java.awt.Dimension(7, 70));
        montoMovimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                montoMovimientoFocusGained(evt);
            }
        });
        montoMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoMovimientoActionPerformed(evt);
            }
        });

        jLabel2.setText("SELECCIONAR CUENTA");

        jButton1.setBackground(new java.awt.Color(0, 25, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tipoCuenta.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Cargar");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        tipoCuenta.add(jRadioButton2);
        jRadioButton2.setText("Abonar");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("MONTO");

        jLabel4.setText("ACCION");

        nombreNuevaCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreNuevaCuenta.setText("Nueva cuenta");
        nombreNuevaCuenta.setToolTipText("Cuenta");
        nombreNuevaCuenta.setMaximumSize(new java.awt.Dimension(150, 25));
        nombreNuevaCuenta.setMinimumSize(new java.awt.Dimension(150, 25));
        nombreNuevaCuenta.setPreferredSize(new java.awt.Dimension(150, 25));
        nombreNuevaCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreNuevaCuentaFocusGained(evt);
            }
        });
        nombreNuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreNuevaCuentaActionPerformed(evt);
            }
        });

        Crear.setText("NC");
        Crear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CrearStateChanged(evt);
            }
        });
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        Tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "D", "H" }));
        Tipo.setToolTipText("");

        aplicaIva.setText("IVA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(comboListaCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(Crear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aplicaIva)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(jLabel3)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4)
                                .addGap(95, 95, 95))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 197, Short.MAX_VALUE)
                                .addComponent(montoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(65, 65, 65)))))
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboListaCuentas, nombreNuevaCuenta});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(montoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboListaCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aplicaIva)
                            .addComponent(Crear))
                        .addGap(6, 6, 6)
                        .addComponent(nombreNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(0, 25, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 25, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(157, 157, 157))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(400, 400, 400))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void montoMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoMovimientoActionPerformed
        
    }//GEN-LAST:event_montoMovimientoActionPerformed

    private void montoMovimientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_montoMovimientoFocusGained
        montoMovimiento.setText("");
    }//GEN-LAST:event_montoMovimientoFocusGained

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!validarMonto())
        {
            JOptionPane.showMessageDialog(null,"El monto no es correcto");
            return;
        }
                
        String tipo;
        if(jRadioButton1.isSelected())
            tipo="D";
        else
            tipo="H";
        
        Double cantidad=Double.parseDouble(montoMovimiento.getText());
        if(aplicaIva.isSelected())
            cantidad=cantidad + 0.13*cantidad;
            
        Movimiento transaccion=new Movimiento(tipo,cantidad);
        if(Crear.isSelected()){
            String var= Tipo.getSelectedItem().toString();
            Cuenta nueva= new Cuenta(nombreNuevaCuenta.getText(), var,transaccion);
            if(isAdd(nueva)){
                JOptionPane.showMessageDialog(null, "YA EXISTE ESA CUENTA");
            }
            else{
                tabla.lineas.add(new LineaTransaccion(nueva, transaccion));      
            }
            combo.addElement(new Cuenta(nombreNuevaCuenta.getText(), var,transaccion ));
            tabla.fireTableDataChanged();
            comboListaCuentas.setVisible(true);
            nombreNuevaCuenta.setVisible(false);
            Tipo.setVisible(false);
            Crear.setSelected(false);
            
        }else{
            if(isAdd((Cuenta) comboListaCuentas.getSelectedItem())){
                JOptionPane.showMessageDialog(null, "YA EXISTE ESA CUENTA");
            }
            else{
                tabla.lineas.add(new LineaTransaccion((Cuenta) comboListaCuentas.getSelectedItem(), transaccion));      
            }
        
            tabla.fireTableDataChanged(); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboListaCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboListaCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboListaCuentasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(WIDTH);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(total())
            JOptionPane.showMessageDialog(null, "IGUALES");
        else
            JOptionPane.showMessageDialog(null, "NO IGUALES");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        if(Crear.isSelected()){
            comboListaCuentas.setVisible(false);
            nombreNuevaCuenta.setVisible(true);
            Tipo.setVisible(true);
        }else{
            comboListaCuentas.setVisible(true);
            nombreNuevaCuenta.setVisible(false);
            Tipo.setVisible(false);
        }
    }//GEN-LAST:event_CrearActionPerformed

    private boolean validarMonto(){
            //valida si esta vacio
        if(montoMovimiento.getText().isEmpty())
            return false;
        
        Double monto=0.0;
        
        //Valida si es un numero, si lo es lo asigna a monto
        
        try {
            monto = Double.parseDouble(montoMovimiento.getText());
        } catch (Exception e) {
            return false;
        }
        
        //Valida si no es mayor que cero retorna falso
        if(monto < 0)
            return false;
        
        
        //Paso todas las restricciones, retorna true
        return true;
    }
    
    private void nombreNuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreNuevaCuentaActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_nombreNuevaCuentaActionPerformed

    private void CrearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CrearStateChanged

    }//GEN-LAST:event_CrearStateChanged

    private void nombreNuevaCuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreNuevaCuentaFocusGained
        nombreNuevaCuenta.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_nombreNuevaCuentaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Crear;
    private javax.swing.JComboBox Tipo;
    private javax.swing.JCheckBox aplicaIva;
    private javax.swing.JComboBox comboListaCuentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField montoMovimiento;
    private javax.swing.JTextField nombreNuevaCuenta;
    private javax.swing.ButtonGroup tipoCuenta;
    // End of variables declaration//GEN-END:variables
}
